### ISSUE TITLE
Add styling for broken images

### ISSUE THREAD

**Issue by Reedyn** [Reedyn/Saga#85]
http://bitsofco.de/styling-broken-images/

```css
img { 
  /* Same as first example */
  min-height: 5rem;
  position: relative;
}

img:before { 
  content: " ";
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  height: calc(100% + 0px);
  width: 100%;
  background-color: rgb(249, 249, 249);
  border: 1px dotted rgb(181, 181, 181);
  box-sizing: border-box;
}

img:after {
  content: "\f127" " Broken Image of " attr(alt) " (" attr(src) ")";
  display: block;
  font-size: 16px;
  font-style: normal;
  color: rgb(0,0,0,0.7);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  text-align: center;
  line-height: 5rem;
}
```
